### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pump61** [Xzavier0722/ClayTech#3]
[12:51:02 ERROR]: Error occurred while enabling ClayTech vviolet-1.2.23 (Is it up to date?)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cn/claycoffee/ClayTech/implementation/abstractMachines/ACraftingTable.tick(Lorg/bukkit/block/Block;)V @55: invokestatic
  Reason:
    Type 'me/mrCookieSlime/Slimefun/api/inventory/BlockMenu' (current frame, stack[0]) is not assignable to 'me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu'
  Current Frame:
    bci: @55
    flags: { }
    locals: { 'cn/claycoffee/ClayTech/implementation/abstractMachines/ACraftingTable', 'org/bukkit/block/Block', 'me/mrCookieSlime/Slimefun/api/inventory/BlockMenu', integer }
    stack: { 'me/mrCookieSlime/Slimefun/api/inventory/BlockMenu', integer, integer, integer, 'org/bukkit/inventory/ItemStack' }
  Bytecode:
    0000000: 2bb8 003e 4d2a 2bb6 003f 9900 e4b2 0040
    0000010: 2bb9 0029 0200 c000 41b6 0042 3e1d 9e00
    0000020: 692c 071d b200 282b b900 2902 00c0 0024
    0000030: b600 2b2a b600 43b8 0044 2ab6 0045 9900
    0000040: 362a 2bb9 0046 0100 b600 472a b600 48a2
    0000050: 0004 b12a 2bb9 0046 0100 2ab6 0048 b600
    0000060: 49b2 0040 2b1d 0464 b800 4ab9 004b 0300
    0000070: 57a7 007a b200 402b 1d04 64b8 004a b900
    0000080: 4b03 0057 a700 672c 07b2 0016 b800 1712
    0000090: 18b8 0019 b600 4cb2 0028 2bb9 0029 0200
    00000a0: c000 24b6 0027 3a04 1904 be36 0503 3606
    00000b0: 1506 1505 a200 2319 0415 0632 3a07 1907
    00000c0: c600 112c 1907 b600 4d2a b600 1ab6 004e
    00000d0: 5784 0601 a7ff dcb2 0040 2bb9 004f 0200
    00000e0: 57b2 0028 2bb9 004f 0200 57a7 019c 014e
    00000f0: bb00 5059 b700 513a 042a b400 04b9 0021
    0000100: 0100 3a06 1906 b900 2201 0099 00bb 1906
    0000110: b900 2301 00c0 0024 3a07 0336 0519 07b6
    0000120: 0025 3a08 1908 be36 0903 360a 150a 1509
    0000130: a200 7619 0815 0a32 3a0b 2cb2 000d 1505
    0000140: 2eb6 0052 190b 04b8 0053 9900 2119 0bc6
    0000150: 001c 1904 b200 0d15 052e b800 4a19 0bb6
    0000160: 0054 b800 4ab9 004b 0300 572c b200 0d15
    0000170: 052e b600 5219 0ba6 0019 190b c700 1419
    0000180: 0415 05b8 004a 03b8 004a b900 4b03 0057
    0000190: 1505 1008 a200 0984 0501 a700 0603 3605
    00001a0: 840a 01a7 ff89 1904 b900 5501 0019 07b6
    00001b0: 0025 bea0 0009 1907 4ea7 000d 1904 b900
    00001c0: 5601 00a7 ff41 2dc6 00c0 2ab6 0045 9900
    00001d0: 232a 2bb9 0046 0100 b600 472a b600 48a2
    00001e0: 0004 b12a 2bb9 0046 0100 2ab6 0048 b600
    00001f0: 492c b200 0e03 2eb6 0052 c600 1c2c b200
    0000200: 0e03 2eb6 0052 3a06 1906 b600 5719 06b6
    0000210: 0054 a000 04b1 1904 b900 5801 00b9 0059
    0000220: 0100 3a06 1906 b900 2201 0099 0040 1906
    0000230: b900 2301 00c0 005a 3a07 1907 b900 5b01
    0000240: 00c0 0041 b600 429e 0021 2c19 07b9 005c
    0000250: 0100 c000 41b6 0042 1907 b900 5b01 00c0
    0000260: 0041 b600 42b6 005d a7ff bcb2 0028 2b2d
    0000270: b900 4b03 0057 b200 402b 2db6 002b b800
    0000280: 4ab9 004b 0300 57b1
  Stackmap Table:
    append_frame(@83,Object[#200],Integer)
    same_frame(@116)
    same_frame(@135)
    append_frame(@176,Object[#201],Integer,Integer)
    same_frame(@209)
    chop_frame(@215,3)
    chop_frame(@235,1)
    same_frame(@238)
    full_frame(@260,{Object[#99],Object[#202],Object[#200],Object[#36],Object[#203],Top,Object[#172]},{})
    full_frame(@300,{Object[#99],Object[#202],Object[#200],Object[#36],Object[#203],Integer,Object[#172],Object[#36],Object[#201],Integer,Integer},{})
    append_frame(@363,Object[#204])
    same_frame(@400)
    same_frame(@413)
    chop_frame(@416,1)
    chop_frame(@422,3)
    same_frame(@444)
    chop_frame(@454,3)
    same_frame(@483)
    same_frame(@497)
    same_frame(@534)
    append_frame(@548,Top,Object[#172])
    same_frame_extended(@616)
    chop_frame(@619,2)
    chop_frame(@647,2)

        at cn.claycoffee.ClayTech.implementation.items.Machines.<init>(Machines.java:105) ~[?:?]
        at cn.claycoffee.ClayTech.ClayTech.registerSlimefun(ClayTech.java:347) ~[?:?]
        at cn.claycoffee.ClayTech.ClayTech.onEnable(ClayTech.java:181) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-49]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-49]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-49]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-49]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-49]        at java.lang.Thread.run(Thread.java:831) [?:?]
[12:51:02 INFO]: [ClayTech] Disabling ClayTech vviolet-1.2.23

MC Version Paper 1.17.
Java 16

**Comment by Xzavier0722** [comment]
May I have your server environment as well? Include plugins and its version. This looks like you are still using the old CSCoreLib..
